// Inline the extracted CSS into each JS bundle and write the files Admin2 loads.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const TARGETS = [
  { js: 'build/page.js', css: 'build/page.css', out: 'admin-next/pages/maw-menus.js' },
  { js: 'build/field.js', css: 'build/field.css', out: 'admin-next/fields/menus.js' },
];

const banner = '/* MAW Menus — generated by `npm run build` from src/. Do not edit. */\n';

for (const target of TARGETS) {
  const js = readFileSync(target.js, 'utf8');
  const cssFile = [target.css, 'build/style.css'].find(existsSync);
  const css = cssFile ? readFileSync(cssFile, 'utf8') : '';

  if (!js.includes('__MAW_CSS__')) {
    throw new Error(`${target.js} is missing the __MAW_CSS__ placeholder.`);
  }
  // Admin2 evaluates the file from a blob URL, which has no import base: a surviving relative import
  // would 404 at run time with no useful error.
  if (/^\s*import\s.+from\s+['"]\.{1,2}\//m.test(js)) {
    throw new Error(`${target.js} contains relative imports; Admin2 cannot load it.`);
  }

  mkdirSync(dirname(target.out), { recursive: true });
  writeFileSync(target.out, banner + js.replace('"__MAW_CSS__"', JSON.stringify(css)));
  console.log(`${target.out} written (${Math.round((js.length + css.length) / 1024)} KB)`);
}
